version: "3.8"

services:

    nginx:
        build: ./docker/nginx
        ports:
            - "8080:80"
        environment:
            PHP_IDE_CONFIG: serverName=default
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
    php-fpm:
        build: ./docker/php-fpm
        working_dir: /var/www/
        environment:
            PHP_IDE_CONFIG: serverName=default
        volumes:
            - ./:/var/www
            - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa
        depends_on:
            - db
    db:
        image: mysql:5.6.51
        # Показываем наружу порт
        ports:
            - "3336:3306"
        # Задаем параметры для инициализации БД
        environment:
            # Пароль к БД
            MYSQL_ROOT_PASSWORD: root
            # Создаваемая по умолчанию бд
            MYSQL_DATABASE: db
        # Линкуем внешнюю папку для хранения БД
        volumes:
            - "mysql-app-data:/var/lib/mysql:rw"
volumes:
    mysql-app-data:
