Search.appendIndex(
    [
                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand",
            "name": "RegistrationUserCommand",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#method_getName"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#method_setName"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#method_getEmail"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#method_setEmail"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003AgetSourceId\u0028\u0029",
            "name": "getSourceId",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#method_getSourceId"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003AsetSourceId\u0028\u0029",
            "name": "setSourceId",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#method_setSourceId"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#property_name"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#property_email"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserCommand\u003A\u003A\u0024sourceId",
            "name": "sourceId",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserCommand.html#property_sourceId"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserException",
            "name": "RegistrationUserException",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserException.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserHandler",
            "name": "RegistrationUserHandler",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserHandler.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserHandler.html#method___construct"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserHandler.html#method_handle"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\RegistrationUserHandler\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-RegistrationUserHandler.html#property_userRepository"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\UserRequest",
            "name": "UserRequest",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-UserRequest.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\UserResult",
            "name": "UserResult",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-UserResult.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\UserResult\u003A\u003AgetSourceId\u0028\u0029",
            "name": "getSourceId",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-UserResult.html#method_getSourceId"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\UserResult\u003A\u003AsetSourceId\u0028\u0029",
            "name": "setSourceId",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-UserResult.html#method_setSourceId"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser\\UserResult\u003A\u003A\u0024sourceId",
            "name": "sourceId",
            "summary": "",
            "url": "classes/Demo4-Application-Commands-Registration-RegistrationUser-UserResult.html#property_sourceId"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Contracts\\UserCriteriaInterface",
            "name": "UserCriteriaInterface",
            "summary": "",
            "url": "classes/Demo4-Domain-User-Contracts-UserCriteriaInterface.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Contracts\\UserRepositoryInterface",
            "name": "UserRepositoryInterface",
            "summary": "",
            "url": "classes/Demo4-Domain-User-Contracts-UserRepositoryInterface.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Contracts\\UserRepositoryInterface\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "",
            "url": "classes/Demo4-Domain-User-Contracts-UserRepositoryInterface.html#method_findById"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Contracts\\UserRepositoryInterface\u003A\u003AfindByCriteria\u0028\u0029",
            "name": "findByCriteria",
            "summary": "",
            "url": "classes/Demo4-Domain-User-Contracts-UserRepositoryInterface.html#method_findByCriteria"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Contracts\\UserRepositoryInterface\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Demo4-Domain-User-Contracts-UserRepositoryInterface.html#method_save"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Exceptions\\UserNotFoundException",
            "name": "UserNotFoundException",
            "summary": "",
            "url": "classes/Demo4-Domain-User-Exceptions-UserNotFoundException.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserCollection",
            "name": "UserCollection",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserCollection.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserEntity",
            "name": "UserEntity",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserEntity.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserEntity\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserEntity.html#method_getName"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserEntity\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserEntity.html#method_setName"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserEntity\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserEntity.html#method_getEmail"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserEntity\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserEntity.html#method_setEmail"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserEntity\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserEntity.html#property_name"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\UserEntity\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Demo4-Domain-User-UserEntity.html#property_email"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\JsonResponse",
            "name": "JsonResponse",
            "summary": "",
            "url": "classes/Demo4-Infrastructure-JsonResponse.html"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\JsonResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Demo4-Infrastructure-JsonResponse.html#method___construct"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\Repositories\\User\\UserCriteria",
            "name": "UserCriteria",
            "summary": "",
            "url": "classes/Demo4-Infrastructure-Repositories-User-UserCriteria.html"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\Repositories\\User\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/Demo4-Infrastructure-Repositories-User-UserRepository.html"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\Repositories\\User\\UserRepository\u003A\u003AfindById\u0028\u0029",
            "name": "findById",
            "summary": "",
            "url": "classes/Demo4-Infrastructure-Repositories-User-UserRepository.html#method_findById"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\Repositories\\User\\UserRepository\u003A\u003AfindByCriteria\u0028\u0029",
            "name": "findByCriteria",
            "summary": "",
            "url": "classes/Demo4-Infrastructure-Repositories-User-UserRepository.html#method_findByCriteria"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\Repositories\\User\\UserRepository\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "",
            "url": "classes/Demo4-Infrastructure-Repositories-User-UserRepository.html#method_save"
        },                {
            "fqsen": "\\Demo4\\Presentation\\Controllers\\UserController",
            "name": "UserController",
            "summary": "",
            "url": "classes/Demo4-Presentation-Controllers-UserController.html"
        },                {
            "fqsen": "\\Demo4\\Presentation\\Controllers\\UserController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "UserController\u0020constructor.",
            "url": "classes/Demo4-Presentation-Controllers-UserController.html#method___construct"
        },                {
            "fqsen": "\\Demo4\\Presentation\\Controllers\\UserController\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "",
            "url": "classes/Demo4-Presentation-Controllers-UserController.html#method_show"
        },                {
            "fqsen": "\\Demo4\\Presentation\\Controllers\\UserController\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Demo4-Presentation-Controllers-UserController.html#method_create"
        },                {
            "fqsen": "\\Demo4\\Presentation\\Controllers\\UserController\u003A\u003A\u0024userRepository",
            "name": "userRepository",
            "summary": "",
            "url": "classes/Demo4-Presentation-Controllers-UserController.html#property_userRepository"
        },                {
            "fqsen": "\\Demo4\\Presentation\\Controllers\\UserController\u003A\u003A\u0024commandBus",
            "name": "commandBus",
            "summary": "",
            "url": "classes/Demo4-Presentation-Controllers-UserController.html#property_commandBus"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration\\RegistrationUser",
            "name": "RegistrationUser",
            "summary": "",
            "url": "namespaces/demo4-application-commands-registration-registrationuser.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands\\Registration",
            "name": "Registration",
            "summary": "",
            "url": "namespaces/demo4-application-commands-registration.html"
        },                {
            "fqsen": "\\Demo4\\Application\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/demo4-application-commands.html"
        },                {
            "fqsen": "\\Demo4\\Application",
            "name": "Application",
            "summary": "",
            "url": "namespaces/demo4-application.html"
        },                {
            "fqsen": "\\Demo4",
            "name": "Demo4",
            "summary": "",
            "url": "namespaces/demo4.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Contracts",
            "name": "Contracts",
            "summary": "",
            "url": "namespaces/demo4-domain-user-contracts.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/demo4-domain-user-exceptions.html"
        },                {
            "fqsen": "\\Demo4\\Domain\\User",
            "name": "User",
            "summary": "",
            "url": "namespaces/demo4-domain-user.html"
        },                {
            "fqsen": "\\Demo4\\Domain",
            "name": "Domain",
            "summary": "",
            "url": "namespaces/demo4-domain.html"
        },                {
            "fqsen": "\\Demo4\\Infrastructure",
            "name": "Infrastructure",
            "summary": "",
            "url": "namespaces/demo4-infrastructure.html"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\Repositories\\User",
            "name": "User",
            "summary": "",
            "url": "namespaces/demo4-infrastructure-repositories-user.html"
        },                {
            "fqsen": "\\Demo4\\Infrastructure\\Repositories",
            "name": "Repositories",
            "summary": "",
            "url": "namespaces/demo4-infrastructure-repositories.html"
        },                {
            "fqsen": "\\Demo4\\Presentation\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/demo4-presentation-controllers.html"
        },                {
            "fqsen": "\\Demo4\\Presentation",
            "name": "Presentation",
            "summary": "",
            "url": "namespaces/demo4-presentation.html"
        }            ]
);
